name: "Test New Code"
run-name: "Running code tests for ${{github.actor}}"

on:
    push:
        branches:
            - "main"

jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc-version: [13]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        env:
          CC: gcc-${{matrix.gcc-version}}
          CXX: g++-${{matrix.gcc-version}}
        run: chmod +x ./utility.sh
      - name: Build Code
        run: ./utility.sh debug
      - name: Do Tests
        run: ./utility.sh test
