name: "Test New Code"
run-name: "Running code tests for ${{github.actor}}"

on:
    push:
        branches:
            - "main"

jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc-version: [13]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: update-alternatives --set gcc gcc-${{matrix.gcc-version}} && update-alternatives --set g++ g++-${{matrix.gcc-version}} && chmod +x ./utility.sh
      - name: Build Code
        run: ./utility.sh debug
      - name: Do Tests
        run: ./utility.sh test
